# 텐서

- 파이토치의 텐서는 다차원 배열로, 넘파이(Numpy) 배열과 매우 유사하며, 머신 러닝 모델의 입력 데이터, 가중치, 그라디언트 등을 표현하는데 사용

In [1]:
import torch
import numpy as np

### 텐서 생성하는 방법

- 데이터 리스트를 텐서로 변환

In [3]:
data = [[1,2], [3,4]]
print(data)
print(type(data))
x_data = torch.tensor(data)
print(x_data)
print(type(x_data))

[[1, 2], [3, 4]]
<class 'list'>
tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


- Numpy 배열에서 텐서로 변환

In [7]:
np_array = np.array(data)
print(np_array)
print(type(np_array))
x_np = torch.from_numpy(np_array)
print(x_np)
print(type(x_np))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>


- 랜덤값이나 상수값으로 텐서만들기

In [8]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7034, 0.3650, 0.9029],
        [0.3267, 0.4169, 0.4813]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 텐서의 속성 보기

In [9]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### 텐서의 운영시스템 보기

In [10]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


### 넘파이 슬라이싱

In [45]:
tensor = torch.ones(4, 4)
tensor[:2,2] = 0                #  [행: 갯수,열]
print(tensor)

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [54]:
tensor1 = torch.rand(4, 4)
tensor[1:3,2] = 0
print(tensor1)

tensor([[0.7124, 0.9233, 0.2714, 0.1680],
        [0.9047, 0.4229, 0.8150, 0.6490],
        [0.6327, 0.3149, 0.7396, 0.9966],
        [0.2083, 0.0312, 0.4332, 0.0271]])


In [55]:
tensor2 = torch.ones(4, 4)
tensor[:1,3] = 0
print(tensor2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### 텐서 합치기

In [56]:
t1 = torch.cat([tensor, tensor1, tensor2], dim=1)
print(t1)

tensor([[1.0000, 1.0000, 0.0000, 0.0000, 0.7124, 0.9233, 0.2714, 0.1680, 1.0000,
         1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 0.0000, 1.0000, 0.9047, 0.4229, 0.8150, 0.6490, 1.0000,
         1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 0.0000, 1.0000, 0.6327, 0.3149, 0.7396, 0.9966, 1.0000,
         1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 0.2083, 0.0312, 0.4332, 0.0271, 1.0000,
         1.0000, 1.0000, 1.0000]])


### 텐서 끼리 곱하기

In [59]:
# tensor.mul 로 텐서 끼리 곱하기
print(f"tensor.mul(tensor) \n {tensor.mul(tensor1)} \n")
# *로 텐서끼리 곱하기
print(f"tensor * tensor \n {tensor * tensor1}")

tensor.mul(tensor) 
 tensor([[0.7124, 0.9233, 0.0000, 0.0000],
        [0.9047, 0.4229, 0.0000, 0.6490],
        [0.6327, 0.3149, 0.0000, 0.9966],
        [0.2083, 0.0312, 0.4332, 0.0271]]) 

tensor * tensor 
 tensor([[0.7124, 0.9233, 0.0000, 0.0000],
        [0.9047, 0.4229, 0.0000, 0.6490],
        [0.6327, 0.3149, 0.0000, 0.9966],
        [0.2083, 0.0312, 0.4332, 0.0271]])


### 텐서에 전체적으로 특정 숫자 더해주기

In [61]:
print(tensor, "\n")
tensor.add_(3)
print(tensor)

tensor([[6., 6., 5., 5.],
        [6., 6., 5., 6.],
        [6., 6., 5., 6.],
        [6., 6., 6., 6.]]) 

tensor([[9., 9., 8., 8.],
        [9., 9., 8., 9.],
        [9., 9., 8., 9.],
        [9., 9., 9., 9.]])


# numpy와 tensor의 bridge 기능

-파이토치(PyTorch)의 텐서(Tensor)는 CPU 상에서도 동작하는데, 이때 텐서와 넘파이(Numpy) 배열은 서로의 기반 메모리 위치를 공유할 수 있다. 즉, 텐서와 넘파이 배열은 같은 데이터를 가리키게 됩니다. 따라서 하나를 변경하면 다른 하나도 변경되는 특징을 가지고 있다.

-gpu에서는 데이터 공유 발생하지 않는다!

### 텐서에서 넘파이 배열로

In [62]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [64]:
# 텐서에 1을 더하고 같은 메모리 공간을 공유하는 넘파이 배열도 영향받는지 확인해보기
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]
